### ISSUE TITLE
Incorrect order ? with CairoMakie

### ISSUE THREAD

**Issue by kescobo** [PavanChaggar/ConnectomesOld.jl#18]
This may be beyond your control, but using CairoMakie:

```
using Connectomes
using CairoMakie
using ColorSchemes

c = Connectomes.connectomepath() |> Connectome

#-

fig = Figure(resolution=(1200,600))
ax = Axis3(fig[1,1], aspect = :data, azimuth = 0.0pi, elevation=0.0pi)
hidedecorations!(ax)
hidespines!(ax)


for i in 1:83
    plot_roi!(i, get(ColorSchemes.viridis, rand()))
end
 
fig
```

![image](https://user-images.githubusercontent.com/3502975/179578182-aff60841-0815-4c13-a286-3480e6d37930.png)

**Comment by PavanChaggar** [comment]
I think this is a result of CairoMakie not being able to support 3d rendering, see [here](https://makie.juliaplots.org/stable/documentation/backends/cairomakie/#z-order)!
